# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name cholesky_diagonalcpp
#' @title Cholesky diagonal update
#' 
#' @description It calculates the Cholesky factor of (A + diag(diagadd)) directly from chol(A) and diagadd vector. See Algorithm 2 in Appendix A1 of Lee et al.(2021)
#' 
#' @param R n by n matrix, right triangular Cholesky factor R, where t(R)*R = A 
#' @param diagadd n by 1 vector, diagonal adding vector 
#' @export
#' @references Lee, C. J., Luo, Z. T., & Sang, H. (2021). T-LoHo: A Bayesian Regularization Model for Structured Sparsity and Smoothness on Graphs. \emph{Advances in Neural Information Processing Systems 34 (NeurIPS 2021)}.
#' 
#' @examples
#' 
#' X = matrix(rnorm(1000*200),1000, 200)
#' A = crossprod(X) # positive definite A
#' R = chol(A) 
#' diagadd = runif(200)
#' 
#' Rnew = cholesky_diagonalcpp(R, diagadd) 
#' all.equal(Rnew, chol(crossprod(X)+diag(diagadd)))
#'
NULL

cholesky_diagonalcpp <- function(R, diagadd) {
    .Call(`_TLOHO_cholesky_diagonalcpp`, R, diagadd)
}

